CLUSTAL multiple sequence alignment by MUSCLE (3.8)


Iberian_newt                -MGEMILLRRDLLGGF-ISTLLVPLGLGCGPGRGIGQRRRPQKLTPLAYKQFIPNVSEKT
Mexican_walking_fish        MGEMRLLLRRLLLGTL-VWALLVPSGLTCGPGRGIGKRRQPKKLTPLAYKQFIPNVAEKT
Xenopus_sonic_hedgehog      ------------------------------------------------------------
African_clawed_frog         ----MSVATGILLLGF-TCSLLIPPGLSCGPGRGIGKRRHPKKLTPLVYKQFIPNVAEKT
Burmese_python              ----MLLRRRSGLLPLCLGALFLSAGLACGPGRGFGKRRHPKKLTPLAYKQFIPNVAEKT
Tiger_snake                 ----MLLLRRTGLLPLCLGALFLSAGLACGPGRGFGKRRHPKKLTPLAYKQFIPNVAEKT
Human                       ----MLLLARCLLLVL-VSSLLVCSGLACGPGRGFGKRRHPKKLTPLAYKQFIPNVAEKT
                                                                                        

Iberian_newt                LGASGRYEVKITRNSERFQELTPNYNPDIIFKVEENTGADRLMTQRCKDKLNSLAISVMN
Mexican_walking_fish        LGASGRYEGKITRNSDRFKELTPNYNPDIIFKDEENTGADRLMTQRCKDKLNALAISVMN
Xenopus_sonic_hedgehog      ------------RNSDRFKELTPNYNPDIIFKDEENTGADRLMTQRCKDKLNALAISVMN
African_clawed_frog         LGASGRYEGKIASNSDRFKELTPNYNPDIVFKDEENTGADRLMTQRCKDKLNALAISVMN
Burmese_python              LGASGRYEGKISRNSERFKELTPNYNPDIIFKDEENTGADRLMTQRCKDKLNALAISVMN
Tiger_snake                 LGASGRYEGKITRNSERFKELTPNYNPDIIFKDEENTGADRLMTQRCKDKLNALAISVMN
Human                       LGASGRYEGKISRNSERFKELTPNYNPDIIFKDEENTGADRLMTQRCKDKLNALAISVMN
                                         **:**:**********:** *******************:*******

Iberian_newt                QWPGVKLRVTEGWDEDGHHSEESLHYEGRAVDITTSDRDRSKYGMLARLAVEAGFDWVYF
Mexican_walking_fish        QWPGVKLRVTEGWDEDGHHSEESLHYEGRAVDITTSDRDRSKYGMLARLAVEAGFDWVYF
Xenopus_sonic_hedgehog      QWPGVKLRVTEGWDEDGHHSEESLHYEGRAVDITTSDRDRSKYGMLARLAVEAGFDWVYF
African_clawed_frog         QWPGVKLRVTEGWDEDGHHLEESLHYEGRAVDITTSDRDRSKYGMLARLAVEAGFDWVYY
Burmese_python              QWPGVKLRVTEGWDEDGHHSEESLHYEGRAVDITTSDRDRSKYGMLARLAVEAGFDWVYY
Tiger_snake                 QWPGVKLRVTEGWDEDGHHSEESLHYEGRAVDITTSDRDRSKYGMLARLAVEAGFDWVYY
Human                       QWPGVKLRVTEGWDEDGHHSEESLHYEGRAVDITTSDRDRSKYGMLARLAVEAGFDWVYY
                            ******************* ***************************************:

Iberian_newt                ESKAHIHCSVKAENSVAVKSGGCFPGSATVTLEQGVRIPVKGLKPGNRVLAVDVEGRLIY
Mexican_walking_fish        ESKAHIHCSVKAENSVAAKSGGCFPASAKVTLEHGVTRPVKDLRPGDRVLAADGQGRLVY
Xenopus_sonic_hedgehog      ESKAHIHCSVKAENSVAAKSGGCFPGSARVMVEPGGTKAVRELRPGDRVLSSDPQGNLIY
African_clawed_frog         ESKAHIHCSVKAENSVAAKSGGCFPAGAEVMVELGGTKAVKDLRPGDRVLSSDAQGNLLY
Burmese_python              ESKAHIHCSVKAENSVAAKSGGCFPGSAWVNLEEGGTKLVKDLRPGDRVLAADVHGQLFY
Tiger_snake                 ESKAHIHCSVKAENSVAAKSGGCFPGSAWVNLEGGGTKLVKDLHPGDRVLAADVHGQLFY
Human                       ESKAHIHCSVKAENSVAAKSGGCFPGSATVHLEQGGTKLVKDLSPGDRVLAADDQGRLLY
                            *****************.*******..* * :* *    *. * **:***: *  *.*.*

Iberian_newt                SDFLLFMDEEE-TARKVFYVIETSLPRERLRLTAAHLLFVAQEHPGNASAGNFRSKFGHR
Mexican_walking_fish        SDFLMFLDKEE-AVTKVFYVIETERPRQRLRLTAAHLLFAAR-HPANSSSST--------
Xenopus_sonic_hedgehog      SDFLLFIDKEH-DVKKLYYVIQTS--QTRIRMTAAHLLFVAQ----SNGTGS--------
African_clawed_frog         SDFLLFIDQQH-DVKKLFYVIETSHPRRRIRLTAAHLLFVAQ----VNGSRS--------
Burmese_python              SEFLAFLDREDPPVHKLFYVIETQRPQTRLLLTAAHLLFVAP--PQNHSHSQ--------
Tiger_snake                 SEFLAFLDREEPPVHKLFYVIETQTPQARLLLTAAHLLFVAP--PHNHSHSQ--------
Human                       SDFLTFLDRDD-GAKKVFYVIETREPRERLLLTAAHLLFVAP--HNDSATGEPEASSGSG
                            *:** *:* :   . *::***:*   . *: :*******.*       .           

Iberian_newt                -------RFRSMFASSVRPGHRVLTEDR--EGRGLREATVDRVYL-EEATGAYAPVTAHG
Mexican_walking_fish        -------GFQSIFASRVRPGHRVLTVDQ--EGRGLQEATVTRVYL-EEGAGAYAPVTSHG
Xenopus_sonic_hedgehog      --------FKSVFASNVRPGDVIYSADR--RDMTLREAMVEKVDL-EEDIGGFCPRNCPG
African_clawed_frog         --------FKSVFASSIQPGDIIYSADP--RAMALNEVKVEKVGL-EEDTGAYAPLTAHG
Burmese_python              --------PQPIFASRVQPGQQVYVLGQ--GGQTLLQAAVHSVSLQEEASGAYAPLTAQG
Tiger_snake                 --------PQPIFASRVQPGQHVYVLAQ--GGQTLLPAAVHSVSLKEEASGAYAPLTAQG
Human                       PPSGGALGPRALFASRVRPGQRVYVVAERDGDRRLLPAAVHSVTLSEEAAGAYAPLTAQG
                                     ..:*** :.**  :           *  . *  * * **  *.:.* .. *

Iberian_newt                TVVIDRVLASCYAVIEEHSWAHWAFAPLRVGFGILSFFSPQ-------------------
Mexican_walking_fish        TVVIDKVLASCYAVIEEHSWAHWAFAPLRLGYGILSIFSPQ-------------------
Xenopus_sonic_hedgehog      ------------------------------------------------------------
African_clawed_frog         TLVIDQVLSSCYALIEEHTWAHLAFAPLRFGLSLSPYLFPK-----------DSSPSPQS
Burmese_python              TILINQVLASCYAVIEEHSWAHWAFAPFRMAHAVLAMLDPE----------------GLS
Tiger_snake                 TILINQVLASCYAVIEEHSWAHWAFAPFRIAHAALAVLNLE----------------GLS
Human                       TILINRVLASCYAVIEEHSWAHRAFAPFRLAHALLAALAPARTDRGGDSGGGDRGGGGGR
                                                                                        

Iberian_newt                ---DYSSHSPPAPS-QAEGVHWYSEILYRIGTWVLQADTIHPLGMAAKSS
Mexican_walking_fish        ---DYSPHSPPAPS-QKEGVHWYSEILYHIGTWVLHSDTIHPWGMAAKSS
Xenopus_sonic_hedgehog      --------------------------------------------------
African_clawed_frog         HHQLDSSPSPQSHH-QPEGIHWYSQLLYQLGTWLLDSNSLHPLGMATKSS
Burmese_python              SPLLFPAAAPEESS-SLAGVHWYSRLLYHIGRWILDSETMHPLGMAS---
Tiger_snake                 SPLLFPAAVPEEGA-SLAGVHWYSRLLYYIGRWILGSEMMHPLGMAS---
Human                       VALTAPGAADAPGAGATAGIHWYSQLLYQIGTWLLDSEALHPLGMAVKSS
                                                                              
